<a href="https://colab.research.google.com/github/mahaairshad-shu/MechanicsPython2025/blob/main/Week%203/Wk3_Sess1_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![SHU](https://drive.google.com/uc?export=view&id=1oauWClN3B2tjg1AeVHtfjAXZg13d9HXL)

#**Modelling Mechanics of Sports Engineering**
##Week 3
###Session 1 - Data Analysis


<a target="_blank" href="https://github.com/mahaairshad-shu/MechanicsPython2025">
  <img alt="Link to GitHub" src="https://img.shields.io/badge/link_to-GitHub_repo-blue?logo=github&labelColor=black">

</a><a target="_blank" href="https://shuspace.shu.ac.uk/ultra/courses/_355862_1/outline">
  <img alt="Access course folder" src="https://img.shields.io/badge/access_course_files-Folder-yellow">
</a>

✅ **Note: Make sure the AI assistant is turned off**

*Tools> Settings> AI assistance> Hide generative AI features*

* Keep saving your changes! ***Ctrl+S***   all the way!

#Pandas

Pandas is a fast, powerful, flexible and easy to use library designed for Python. It is used for data analysis and manipulation.  In particular, it offers data structures and operations for manipulating numerical tables and time series.

![image.png]()

We'll start by installing pandas to our Colab Environment if it doesn't exist.

In [ ]:
# Install pandas if you haven't already
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

## Creating a new dataframe

Creating a DataFrame from a dictionary

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 28],
        'City': ['New York', 'London', 'Paris', 'Tokyo']}
df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo

Creating a DataFrame from a list of lists

In [ ]:
data = [['Alice', 25, 'New York'],
        ['Bob', 30, 'London'],
        ['Charlie', 22, 'Paris'],
        ['David', 28, 'Tokyo']]
df2 = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
df2

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo

 Creating a DataFrame from a list of dictionaries

In [ ]:
data = [{'Name': 'Alice', 'Age': 25, 'City': 'New York'},
        {'Name': 'Bob', 'Age': 30, 'City': 'London'},
        {'Name': 'Charlie', 'Age': 22, 'City': 'Paris'},
        {'Name': 'David', 'Age': 28, 'City': 'Tokyo'}]
df3 = pd.DataFrame(data)
df3

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo

Creating a DataFrame from a NumPy array

In [ ]:
import numpy as np
data = np.array([['Alice', 25, 'New York'],
                 ['Bob', 30, 'London'],
                 ['Charlie', 22, 'Paris'],
                 ['David', 28, 'Tokyo']])

df4 = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
df4

      Name Age      City
0    Alice  25  New York
1      Bob  30    London
2  Charlie  22     Paris
3    David  28     Tokyo

Creating an empty DataFrame

In [ ]:
df5 = pd.DataFrame()
print(df5)

Empty DataFrame
Columns: []
Index: []

##Importing data from csv file

There are multiple ways to import data in colab environment. You can choose any of the following mentioned ways.

####1. The classic way of drag and drop.

- Download the csv file in your PC from the following link

</a><a target="_blank" href="https://drive.google.com/file/d/1oyY1OLOFbBQZJZ0uJNPVe27T86uPko1F/view?usp=drive_link">
  <img alt="Access csv file" src="https://img.shields.io/badge/access_csv_file-Drive_link-yellow">
</a>


- Goto the Files tab on the left

![image.png]()

- Either use the 'Upload to session storage' button or drag and drop the downloaded file here

![image.png]()

- Your file should start appearing here

![image.png]()

*Remember that the file is temporarily stored during a session and is deleted when the session is closed or restarted.*

- We'll load the csv file as a dataframe now.
- Right click the file and 'Copy path'. Paste it in the 'file_loc' string below

In [ ]:
file_loc = '/content/users_dataset.csv'
df = pd.read_csv(file_loc)

df

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016,IT sales professional

When working with a large dataframe we can use df.head() to view the first 5 rows

In [ ]:
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938,Veterinary surgeon

to view the last 5 rows of your df you can use

In [ ]:
df.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016,IT sales professional

#### 2. Loading from a public drive link

In [ ]:
drive_link = 'https://drive.google.com/file/d/1oyY1OLOFbBQZJZ0uJNPVe27T86uPko1F/view?usp=drive_link'
url='https://drive.google.com/uc?id=' + drive_link.split('/')[-2]
df = pd.read_csv(url)

df.head()

####3. Load from a location in your drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/users_dataset.csv')
df.head()

##Accessing data

**Rows are accessed with Indexes**


**Columns are accessed with Column Names**

![image.png]()

In [ ]:
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1971,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1968,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,1980,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1968,Veterinary surgeon

####Accessing columns

In [ ]:
# Accessing columns
print("\nAccessing the 'First Name' column:")
df['First Name'].head()

Accessing the 'First Name' column:

0      Shelby
1     Phillip
2    Kristine
3     Yesenia
4        Lori
Name: First Name, dtype: object

####Accessing rows using index

In [ ]:
# Accessing rows using index
print("\nAccessing the first row:")
df.iloc[0]

Accessing the first row:

Index                                 1
User Id                 88F7B33d2bcf9f5
First Name                       Shelby
Last Name                       Terrell
Sex                                Male
Email              elijah57@example.net
Phone            001-084-906-7849x73518
Year of Birth                      1971
Job Title               Games developer
Name: 0, dtype: object

####Accessing a specific cell value

In [ ]:
# Accessing a specific cell value
print("\nAccessing the value in the first row and 'Last Name' column:")
df.loc[0, 'Last Name']

Accessing the value in the first row and 'Last Name' column:

'Terrell'

####Filtering data

In [ ]:
# Filtering data
print("\nFiltering for female users:")
df[df['Sex'] == 'Female'].head()

Filtering for female users:

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist
6,7,bE9EEf34cB72AF7,Katherine,NaN,Female,conniecowan@example.com,+1-773-151-6685x49162,1974,Intelligence analyst
10,11,BF0BbA03C29Bb3b,Sheila,Ross,Female,huangcathy@example.com,895.881.4746,1971,Advertising account executive
13,14,b759b74BD1dE80d,Bridget,Nash,Female,mercedes44@example.com,(216)627-8359,1972,Social worker
15,16,50Bb061cB30B461,Thomas,Knight,Female,braunpriscilla@example.net,+1-360-880-0766,1998,Sport and exercise psychologist

####Boolean indexing (more complex filtering)

In [ ]:
print("Older male users:\n")
df[(df['Sex'] == 'Male') & (df['Year of Birth'] < 1970)].head()

Older male users:

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
2,3,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1968,Homeopath
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1968,Veterinary surgeon
5,6,bfDD7CDEF5D865B,Erin,Day,Male,tconner@example.org,001-171-649-9856x5553,1945,Waste management officer
9,10,8e4FB470FE19bF0,Isaiah,Downs,Male,virginiaterrell@example.org,+1-511-372-1544x8206,1966,"Engineer, site"
11,12,F738c69fB34E62E,Stacy,Newton,Male,rayleroy@example.org,710.673.3213x80335,1949,Warden/ranger

####Accessing multiple columns

In [ ]:
# Accessing multiple columns
print("\nAccessing the 'First Name' and 'Last Name' columns:")
df[['First Name', 'Last Name']].head()

Accessing the 'First Name' and 'Last Name' columns:

  First Name Last Name
0     Shelby   Terrell
1    Phillip   Summers
2   Kristine       NaN
3    Yesenia  Martinez
4       Lori      Todd

####Accessing a slice of rows

In [ ]:
# Accessing a slice of rows
print("\nAccessing rows 1 through 3:")
df[1:4] # Note: this is exclusive of the upper limit

Accessing rows 1 through 3:

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Year of Birth,Job Title
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1968,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,1980,Market researcher

####Iterating through rows

In [ ]:
# Iterating through rows
print("\nIterating through rows:")
for index, row in df.iterrows():
    print(f"User: {row['First Name']}, Job Title: {row['Job Title']}")

Iterating through rows:
User: Shelby, Job Title: Games developer
User: Phillip, Job Title: Phytotherapist
User: Kristine, Job Title: Homeopath
User: Yesenia, Job Title: Market researcher
User: Lori, Job Title: Veterinary surgeon
User: Erin, Job Title: Waste management officer
User: Katherine, Job Title: Intelligence analyst
User: Ricardo, Job Title: Hydrogeologist
User: Dave, Job Title: Lawyer
User: Isaiah, Job Title: Engineer, site
User: Sheila, Job Title: Advertising account executive
User: Stacy, Job Title: Warden/ranger
User: Mandy, Job Title: Scientist, clinical (histocompatibility and immunogenetics)
User: Bridget, Job Title: Social worker
User: Crystal, Job Title: Agricultural consultant
User: Thomas, Job Title: Sport and exercise psychologist
User: Maurice, Job Title: Secretary/administrator
User: Frank, Job Title: Audiological scientist
User: Alvin, Job Title: Teacher, adult education
User: Jared, Job Title: Paediatric nurse
User: Jacqueline, Job Title: Scientist, marine
User: Colleen, Job Title: Commercial horticulturist
User: Randy, Job Title: Outdoor activities/education manager
User: Janice, Job Title: Drilling engineer
User: Alfred, Job Title: Systems analyst
User: Sean, Job Title: Conservation officer, nature
User: Louis, Job Title: Counsellor
User: Brittney, Job Title: Recycling officer
User: Judy, Job Title: Art gallery manager
User: Norman, Job Title: Gaffer
User: Isaiah, Job Title: Food technologist
User: Jacqueline, Job Title: Building services engineer
User: Bonnie, Job Title: Seismic interpreter
User: Brandon, Job Title: Engineer, biomedical
User: Jackson, Job Title: Set designer
User: Melody, Job Title: Research scientist (life sciences)
User: Leonard, Job Title: Accountant, chartered management
User: Gene, Job Title: Surveyor, quantity
User: Cynthia, Job Title: Outdoor activities/education manager
User: Tanya, Job Title: Information systems manager
User: Matthew, Job Title: Scientist, clinical (histocompatibility and immunogenetics)
User: Kirk, Job Title: Accounting technician
User: Willie, Job Title: Management consultant
User: Miguel, Job Title: Make
User: Darren, Job Title: Retail banker
User: Haley, Job Title: Commissioning editor
User: Danielle, Job Title: Accountant, chartered management
User: Becky, Job Title: Seismic interpreter
User: Caitlyn, Job Title: Jewellery designer
User: Joshua, Job Title: Education officer, museum
User: Heidi, Job Title: Estate manager/land agent
User: Brian, Job Title: Physiotherapist
User: Beverly, Job Title: Passenger transport manager
User: Nathaniel, Job Title: Call centre manager
User: Debra, Job Title: Special educational needs teacher
User: Mackenzie, Job Title: Museum/gallery exhibitions officer
User: Courtney, Job Title: Pension scheme manager
User: Fred, Job Title: Archaeologist
User: Ryan, Job Title: Historic buildings inspector/conservation officer
User: Grace, Job Title: Petroleum engineer
User: Shari, Job Title: Curator
User: Kelli, Job Title: Retail banker
User: Jackie, Job Title: Neurosurgeon
User: Leslie, Job Title: Chiropractor
User: Harold, Job Title: Biochemist, clinical
User: Larry, Job Title: Scientist, water quality
User: Mike, Job Title: Hydrologist
User: Brittney, Job Title: Biochemist, clinical
User: Frank, Job Title: Hospital pharmacist
User: Sandra, Job Title: Warehouse manager
User: Ryan, Job Title: Physiological scientist
User: Tamara, Job Title: English as a second language teacher
User: Jean, Job Title: Financial trader
User: Veronica, Job Title: Structural engineer
User: Kim, Job Title: Biochemist, clinical
User: Tina, Job Title: Race relations officer
User: Jonathon, Job Title: Psychologist, forensic
User: Jermaine, Job Title: Newspaper journalist
User: Regina, Job Title: Public house manager
User: Terrence, Job Title: Careers information officer
User: Tyler, Job Title: Economist
User: Andrew, Job Title: Jewellery designer
User: Reginald, Job Title: Contracting civil engineer
User: Douglas, Job Title: Higher education lecturer
User: Helen, Job Title: Lecturer, further education
User: Mario, Job Title: Research scientist (life sciences)
User: Chelsea, Job Title: Teacher, early years/pre
User: Dustin, Job Title: Travel agency manager
User: Harry, Job Title: Technical sales engineer
User: Kathy, Job Title: Charity fundraiser
User: Alison, Job Title: Patent attorney
User: Jamie, Job Title: Conservator, furniture
User: Melody, Job Title: Dance movement psychotherapist
User: Xavier, Job Title: Financial planner
User: Dillon, Job Title: Air broker
User: Dennis, Job Title: Software engineer
User: Steve, Job Title: Barrister
User: Wesley, Job Title: Police officer
User: Summer, Job Title: Broadcast journalist
User: Mariah, Job Title: IT sales professional

##Manipulating data

####Columns

####Rename a column

In [ ]:
df = df.rename(columns={"Year of Birth": "YOB"})
df.columns

Index(['Index', 'User Id', 'First Name', 'Last Name', 'Sex', 'Email', 'Phone',
       'YOB', 'Job Title'],
      dtype='object')

####Add a new column

In [ ]:
import numpy as np
df['Salary'] = np.random.randint(4000, 8000, size=len(df)) #Adding a Salary column
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1971,Games developer,7162
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist,4758
2,3,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1968,Homeopath,4944
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,1980,Market researcher,4318
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1968,Veterinary surgeon,7011

####Delete a column

In [ ]:
#We can delete the Index column here as its unneccessary
del df['Index']
df.head()

,User Id,First Name,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
0,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1971,Games developer,7162
1,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist,4758
2,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1968,Homeopath,4944
3,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,1980,Market researcher,4318
4,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1968,Veterinary surgeon,7011

###Rows

####Adding a new row

In [ ]:
# Adding a new row
new_row = pd.DataFrame({'First Name': ['Alice'], 'Last Name': ['Smith'], 'Sex': ['Female'], 'YOB': [1985], 'Job Title': ['Data Scientist'], 'Salary':6000})
df = pd.concat([df, new_row], ignore_index=True)
df.tail() #Check the last few rows to see if the new row was added

,User Id,First Name,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
96,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1971,Barrister,4503
97,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1958,Police officer,6919
98,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,1973,Broadcast journalist,4236
99,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,1987,IT sales professional,6083
100,NaN,Alice,Smith,Female,NaN,NaN,1985,Data Scientist,6000

####Deleting a row

In [ ]:
# Deleting a row
df = df.drop(index=df.index[-1]) #Delete the last row
df.tail()

,User Id,First Name,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
95,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1971,Software engineer,5373
96,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1971,Barrister,4503
97,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1958,Police officer,6919
98,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,1973,Broadcast journalist,4236
99,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,1987,IT sales professional,6083

####Modifying an existing row

In [ ]:
#Modifying an existing row
df.loc[df.index[-1], 'Salary'] = 8000 #Modify the salary of the last row
df.tail()

,User Id,First Name,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
95,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1971,Software engineer,5373
96,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1971,Barrister,4503
97,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1958,Police officer,6919
98,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,1973,Broadcast journalist,4236
99,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,1987,IT sales professional,8000

####Conditional modification of rows

In [ ]:
#Conditional modification of rows
df.loc[df['Sex'] == 'Female', 'Salary'] = df.loc[df['Sex'] == 'Female', 'Salary'] * 1.1 #Increase salary of female users by 10%
df.head()

<ipython-input-47-8b666ea4d70a>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[5233.8 7251.2 4584.8 8748.3 7220.4 5223.9 5927.9 7337.  7701.1 5709.
 6050.  7538.3 4590.3 5514.3 8611.9 5570.4 5388.9 8215.9 4483.6 4592.5
 4970.9 6635.2 6098.4 4581.5 6556.  8768.1 6635.2 5894.9 7396.4 5508.8
 5269.  4673.9 5525.3 5436.2 8666.9 6932.2 6999.3 5623.2 5638.6 7152.2
 5596.8 8526.1 8791.2 5647.4 8482.1 6307.4 5397.7 5285.5 6575.8 4480.3
 5910.3 4953.3 4659.6]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Sex'] == 'Female', 'Salary'] = df.loc[df['Sex'] == 'Female', 'Salary'] * 1.1 #Increase salary of female users by 10%

,User Id,First Name,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
0,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1971,Games developer,7162.0
1,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist,5233.8
2,DbeAb8CcdfeFC2c,Kristine,NaN,Male,bthompson@example.com,277.609.7938,1968,Homeopath,4944.0
3,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,1980,Market researcher,4318.0
4,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1968,Veterinary surgeon,7011.0

####Drop the rows with missing values

In [ ]:
# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())
print('\ncurrent len: ', len(df))

Missing Values:
User Id        0
First Name     0
Last Name     10
Sex            0
Email          0
Phone          0
YOB            0
Job Title      0
Salary         0
dtype: int64

current len:  100

In [ ]:
# drop rows with missing values
df = df.dropna() #drops all rows having a NaN value
print(df.isnull().sum())
print('\new len: ', len(df))

User Id       0
First Name    0
Last Name     0
Sex           0
Email         0
Phone         0
YOB           0
Job Title     0
Salary        0
dtype: int64

ew len:  90

####Turn a column into Index. Instead of using numbers as row indexes.

In [ ]:
# Set a new index
df = df.set_index('First Name') # Setting the index to the "First Name" column
print("\nDataFrame with 'First Name' as index:")
df.head()

DataFrame with 'First Name' as index:

,User Id,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
First Name,,,,,,,,
Shelby,88F7B33d2bcf9f5,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1971,Games developer,7162.0
Phillip,f90cD3E76f1A9b9,Summers,Female,bethany14@example.com,214.112.6044x4913,1987,Phytotherapist,5233.8
Yesenia,A31Bee3c201ef58,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,1980,Market researcher,4318.0
Lori,1bA7A3dc874da3c,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1968,Veterinary surgeon,7011.0
Erin,bfDD7CDEF5D865B,Day,Male,tconner@example.org,001-171-649-9856x5553,1945,Waste management officer,4272.0

####The First Names can now be used to access the row

In [ ]:
# Using first names to access the row
print("\nAccessing Bridget's Last Name:")
df.loc['Bridget','Last Name']

Accessing Bridget's Last Name:

'Nash'

####Indexes can also be sorted to sort the order of the rows

In [ ]:
#Sort index
df = df.sort_index()
print("\nDataFrame with sorted index:")
df.head()

DataFrame with sorted index:

,User Id,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
First Name,,,,,,,,
Alfred,c5B09fb33e8bA0A,Mcneil,Female,cassandramorris@example.com,(468)276-9509x53058,1977,Systems analyst,5709.0
Alison,F0aeC9c2759F3C6,Nixon,Female,zmiles@example.net,3506680871,1975,Patent attorney,5397.7
Alvin,7F7E1BAcb0C9AFf,Paul,Male,gilbertdonaldson@example.com,219.436.0887x07551,1973,"Teacher, adult education",5584.0
Andrew,E1cB5cA8CA7CC0a,Waters,Male,nhall@example.net,+1-376-865-2765x3351,1983,Jewellery designer,6315.0
Becky,Ee4eB129dC7913A,Brady,Male,erikmueller@example.org,(390)002-0863,1977,Seismic interpreter,5840.0

###Data type

In [ ]:
# Data type checking and conversion (if needed)
print("\nData Types:")
print(df.dtypes) #strings are loaded as object type from a csv by default

Data Types:
User Id       object
Last Name     object
Sex           object
Email         object
Phone         object
YOB            int64
Job Title     object
Salary       float64
dtype: object

####Convert a data type

In [ ]:
df['Salary'] = df['Salary'].astype(float) #convert to float
print(df.dtypes)

User Id       object
Last Name     object
Sex           object
Email         object
Phone         object
YOB            int64
Job Title     object
Salary       float64
dtype: object

###Save a df as csv

In [ ]:
df.to_csv('users_dataset.csv', index=False)

##Statistics Summary

Pandas has a feature to print statistics summary for the numerical data in the df

In [ ]:
print("\nSummary Statistics:")
print(df.describe())

Summary Statistics:
               YOB       Salary
count    90.000000    90.000000
mean   1972.244444  6293.538889
std      12.735257  1213.031407
min    1945.000000  4027.000000
25%    1967.250000  5439.150000
50%    1972.000000  6154.200000
75%    1980.000000  7159.550000
max    1999.000000  8791.200000

In [ ]:
# Specific statistics
print("\nMean YOB:", df['YOB'].mean())
print("Median Salary:", df['Salary'].median())

Mean YOB: 1972.2444444444445
Median Salary: 6154.200000000001

###Practice

❗Add an 'Age' column to the df ❗

❗Add a pension eligibility column for every employee over the age of 65❗


❗Find and print details of the highest paid Female employee ❗


❗Estimate how many users are paid higher than average salary ❗

In [ ]:
# Write your code here

df.head()

,User Id,Last Name,Sex,Email,Phone,YOB,Job Title,Salary
First Name,,,,,,,,
Alfred,c5B09fb33e8bA0A,Mcneil,Female,cassandramorris@example.com,(468)276-9509x53058,1977,Systems analyst,5709.0
Alison,F0aeC9c2759F3C6,Nixon,Female,zmiles@example.net,3506680871,1975,Patent attorney,5397.7
Alvin,7F7E1BAcb0C9AFf,Paul,Male,gilbertdonaldson@example.com,219.436.0887x07551,1973,"Teacher, adult education",5584.0
Andrew,E1cB5cA8CA7CC0a,Waters,Male,nhall@example.net,+1-376-865-2765x3351,1983,Jewellery designer,6315.0
Becky,Ee4eB129dC7913A,Brady,Male,erikmueller@example.org,(390)002-0863,1977,Seismic interpreter,5840.0